Vagrant.configure(2) do |config|

  config.vm.box = "bento/freebsd-12.1"
  config.vm.guest = :freebsd
  config.ssh.shell = "/bin/sh"

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
  end

  # Disabled the default synced folder.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y git \
       autoconf \
       automake \
       bash \
       ccache \
       gcc \
       jansson \
       jq \
       libtool \
       libyaml \
       libnet \
       pkgconf \
       pcre \
       python \
       rsync \
       rust \
       tex-dvipsk \
       tex-formats
    sudo -u vagrant cargo install cbindgen
    echo "export PATH=/home/vagrant/.cargo/bin:$PATH" > /home/vagrant/.profile
  SHELL

end
